/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jpintamvc.miVentanasPinta;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 * Clase de la ventana VISOR de foto
 * @author Sergio Teacher
 */
public class Ventana3Visor extends javax.swing.JFrame {

    /**
     * Constructor de la ventana Visor
     */
    public Ventana3Visor() {
        initComponents();
        System.out.println("Lanzando la ventana VISOR");
        setBounds(0,0,400,300);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraHerramientas = new javax.swing.JToolBar();
        btnAbrir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtFoto = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraHerramientas.setBackground(new java.awt.Color(0, 255, 204));
        BarraHerramientas.setRollover(true);

        btnAbrir.setBackground(new java.awt.Color(153, 204, 255));
        btnAbrir.setText("💾 Abrir");
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramientas.add(btnAbrir);

        btnLimpiar.setBackground(new java.awt.Color(255, 204, 153));
        btnLimpiar.setText("💣 Limpiar");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramientas.add(btnLimpiar);

        getContentPane().add(BarraHerramientas, java.awt.BorderLayout.PAGE_START);

        txtFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtFoto, java.awt.BorderLayout.CENTER);

        txtEstado.setText("Img:");
        getContentPane().add(txtEstado, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar BarraHerramientas;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtFoto;
    // End of variables declaration//GEN-END:variables

    /**
    * Doy control selectivo, sólo a la capacidad de cargar una imagen.
    */
    public void setIconTxtFoto(ImageIcon MiImagen) {
        System.out.println("Insertando foto");
        this.txtFoto.setIcon(MiImagen);
    }

    /**
    * Doy control selectivo, sólo a la capacidad de escribir.
    */
    public void escribeTxtEstado(String s) {
        txtEstado.setText(s);
        System.out.println(s);
    }

    /**
    * Doy control total del Botón Abrir
    */
    public JButton getBtnAbrir() {
        return btnAbrir;
    }

    /**
    * Doy control total del Botón Limpiar
    */
    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }


}
